Ext.define('CarTracker.view.car.Detail', {
    extend: 'Ext.window.Window',
    alias: 'widget.car.detail',
    modal: true,
    bodyPadding:10,
    width: 800,
    minHeight:600,
    iconCls: 'icon_detail',
    initComponent: function() {
        var me = this;
        Ext.applyIf(me, {
            tpl: Ext.create('Ext.XTemplate', 
                '<table cellpadding="0" cellspacing="0" border="0" class="cardetails">',
                    '<tr>',
                        '<td>',
                            '<tpl for="ImagePaths">',
                                '<div class="thumbnail">',
                                    '<img src="{.}" height="60" data-qtip="<img src={.} />" />',
                                '</div>',
                            '</tpl>',
                        '</td>',
                        '<td>',
                            '<h1>{Year} {_Make} {_Model}</h1>',
                            '<table cellpadding="0" cellspacing="0" border="0" class="carnotes">',
                                '<tr>',
                                    '<td class="label">Category:</td>',
                                    '<td>{_Category}</td>',
                                    '<td class="label">Color:</td>',
                                    '<td>{_Color}</td>',
                                '</tr>',
                                '<tr>',
                                    '<td class="label">VIN #:</td>',
                                    '<td>{VIN}</td>',
                                    '<td class="label">Stock #:</td>',
                                    '<td>{StockNumber}</td>',
                                '</tr>',
                                '<tr>',
                                    '<td class="label">Mileage:</td>',
                                    '<td>{Mileage:number( "0,000" )}</td>',
                                    '<td class="label">Fuel:</td>',
                                    '<td>{Fuel}</td>',
                                '</tr>',
                                '<tr>',
                                    '<td class="label">Engine:</td>',
                                    '<td>{Engine}</td>',
                                    '<td class="label">Transmission:</td>',
                                    '<td>{Transmission}</td>',
                                '</tr>',
                                '<tr>',
                                    '<td colspan="4">{Description}</td>',
                                '</tr>',
                                '<tr>',
                                    '<td colspan="4" class="label">Features:</td>',
                                '</tr>',
                                '<tr>',
                                    '<td colspan="2">',
                                        '<table cellspacing="0" cellpadding="0" border="0" width="100%">',
                                            '<tpl for="_Features">',
                                                '<tpl if="xindex==1 || xindex%2==1">',
                                                    '<tr>',
                                                '</tpl>',
                                                '<td><li>{.}</li></td>',
                                                '<tpl if="xindex%2==0">',
                                                    '</tr>',
                                                '</tpl>',
                                                '<tpl if="xindex%2==1 && xindex==xcount">',
                                                    '<td>&nbsp;</td>',
                                                    '</tr>',
                                                '</tpl>',
                                            '</tpl>',
                                        '</table>',
                                    '</td>',
                                    '<td colspan="2">&nbsp;</td>',
                                '</tr>',
                                '<tr>',
                                    '<td class="label">Acquired:</td>',
                                    '<td>{AcquisitionDate:date( "Y-m-d" )}</td>',
                                    '<td class="label">List Price:</td>',
                                    '<td>{ListPrice:usMoney}</td>',
                                '</tr>',
                                '<tr>',
                                    '<td class="label">Sold?:</td>',
                                    '<td>{IsSold:yesNo}</td>',
                                    '<td class="label">Sale Price:</td>',
                                    '<td>{SalePrice:usMoney}</td>',
                                '</tr>',
                                '<tr>',
                                    '<td class="label">Sales Team:</td>',
                                    '<td colspan="3">',
                                        '<ul style="margin:0px 0px 0px 10px;padding:0px;">',
                                            '<tpl for="_SalesPeople">',
                                                '<li>{.}</li>',
                                            '</tpl>',
                                        '</ul>',
                                    '</td>',
                                '</tr>',
                            '</table>',
                        '</td>',
                    '</tr>',
                '</table>'
            )
        });
        me.callParent( arguments );
    }
});